openai_keys:
  gpt-3.5-turbo-16k:
    - api_key: XXX
      api_base: https://example.com
      api_type: azure
      api_version: XXX
      engine: GPT-35-Turbo-16k
      # you can use any kwargs supported by openai.ChatCompletion here
    - api_key: sk-xxxxx
      organization: org-xxxxxx
      model: gpt-3.5-turbo-16k
  gpt-4:    
    - api_key: sk-xxxxx
      organization: org-xxxxx
      model: gpt-4
    - api_key: sk-xxxxx
      organization: org-xxxxxx
      model: gpt-4
  gpt-4-32k:
    - api_key: XXX
      api_base: XXX
      api_type: XXX
      api_version: XXX
      engine: gpt4-32

default_completion_kwargs:
  model: gpt-4-32k
  temperature: 0.5
  request_timeout: 60

enable_summary: true
summary:
  single_action_max_length: 8192
  max_return_length: 18432

use_selfhost_toolserver: true
selfhost_toolserver_url: http://localhost:8080

max_retry_times: 3
max_subtask_chain_length: 20
max_plan_refine_chain_length: 3
max_plan_tree_depth: 3
max_plan_tree_width: 5
max_plan_length: 8192

rapidapi_retrieve_tool_count: 0

enable_ask_human_for_help: False
enable_self_evolve: False
